{% set name = "seqfu" %}
{% set version = "0.1.0" %}
{% set sha256 = "9f87b16e7144a07143a2c5deed6a849f56eced7956c931f832baac738a170f9f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/quadram-institute-bioscience/{{ name }}/archive/v.{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - any2fasta
    - interleafq
    - n50
    - perl
    - perl-app-cpanminus
    - perl-exporter
    - perl-fastx-abi
    - perl-fastx-reader
    - perl-file-which
    - perl-getopt-long
    - perl-json-pp
    - perl-pod-usage
    - perl-text-asciitable


  run:
    - interleafq
    - n50
    - perl
    - perl-exporter
    - perl-fastx-ab1
    - perl-fastx-reader
    - perl-file-which
    - perl-getopt-long
    - perl-json-pp
    - perl-pod-usage
    - perl-text-asciitable

test:
  files:
    - test.fa
  commands:
  # (see run_test.sh for remainder of tests)
  # Perl 'use' tests
    - perl -e "use FASTX::Reader"
    - perl -e "use FASTX::Abi"
    - perl -e "use Proch::N50"


about:
  home: http://github.com/quadram-institute-bioscience/seqfu/
  license: mit
  summary: 'DNA sequence utilities (N50, de/interleave FASTQ, grep etc.)'

extra:
  identifiers:
    - biotools:{{ name }}
