{% set name = "seqfu-utils" %}
{% set version = "1.0.0" %}
{% set sha256 = " " %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/quadram-institute-bioscience/seqfu/archive/v.{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-app-cpanminus
  run:
    - perl
    - perl-file-which
    - perl-getopt-long
    - perl-json-pp
    - perl-fastx-reader >=0.88
    - perl-fastx-abi
    - perl-exporter
    - perl-text-asciitable
    - perl-pod-usage
    - perl-biox-seq
    - n50 >=1.3.0


test:
  commands:
  # (see run_test.sh for remainder of tests)
  # Perl 'use' tests
    - perl -e "use FASTX::Reader"
    - perl -e "use FASTX::Abi"
    - perl -e "use Proch::N50"
    - perl -e "use BioX::Seq::Stream"


about:
  home: http://github.com/quadram-institute-bioscience/seqfu/
  license: mit
  summary: 'DNA sequence utilities and helpers scripts for the "seqfu" package'
  description: |
    A collection of utilities to work with FASTX (FASTA or FASTQ) files
    using the FASTX::Reader module that accepts gzipped input.
    'n50' will calculate N50, minimum, maximum and total size of the
    sequences in one or more files, supporting CSV, TSV, JSON and screen
    friendly output.
