{% set name = "n50" %}
{% set version = "0.92" %}
{% set sha256 = "b73ee417e56a99f45dac4fc9c8238bed857b6d39acf11c59453c45276fdd1716" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PR/PROCH/Proch-N50-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - n50
    - interleafq
    - any2fasta
    - perl
    - perl-app-cpanminus
    - perl-file-which
    - perl-json-pp
    - perl-fastx-reader
    - perl-fastx-abi
    - perl-getopt-long
    - perl-exporter
    - perl-text-asciitable
    - perl-pod-usage

  run:
    - perl
    - perl-file-which
    - perl-getopt-long
    - perl-json-pp
    - perl-fastx-reader
    - perl-fastx-ab1
    - perl-exporter
    - perl-text-asciitable
    - perl-pod-usage
    - n50
    - interleafq

test:
  files:
    - test.fa
  commands:
  # (see run_test.sh for remainder of tests)
  # Perl 'use' tests
    - perl -e "use FASTX::Reader"
    - perl -e "use Proch::N50"


about:
  home: http://github.com/quadram-institute-bioscience/seqfu/
  license: mit
  summary: 'DNA sequence utilities (N50, de/interleave FASTQ, grep etc.)'
